<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>LookingGlass.DevTool</RootNamespace>
    <AssemblyName>lgdev</AssemblyName>
    <RollForward>LatestMajor</RollForward>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LookingGlass.Core\LookingGlass.Core.csproj" />
  </ItemGroup>

</Project>
